# Bem-vindo(a) a 4° aula de Data Science

### Nessa aula veremos os principais métodos *pandas* para fazer análise exploratória.

Métodos:

  - rename : renomeia os 'rótulos' dos eixos (índices ou colunas)

  - apply : aplica uma determinada função ao longo de um eixo quando for chamado diretamente pelo DataFrame ou aplica uma função numa Series em questão

  - map : "mapeia" uma Series aplicando determinada função a cada elemento desta

  - agg : agrega uma ou mais operações à uma Series

  - min : retorna o valor mínimo de uma Series

  - max : retorna o valor máximo de uma Series

  - sum : retorna a soma dos valores de uma Series

  - mean : retorna a média dos valores de uma Series

  - count : conta as células não vazias de cada linha ou coluna

  - value_counts : retorna uma Series contendo a contagem de linhas exclusivas no DataFrame

  - sort_values : classifica / ordena os valores ao longo de qualquer eixo

  - insert : insire uma nova coluna no DataFrame no local especificado

  - drop : remova linhas ou colunas especificando diretamente seus nomes

Vamos criar nosso próprio DataFrame

In [2]:
# Importando a biblioteca Pandas
import pandas as pd

In [3]:
df = pd.DataFrame({
    'nome': ['José', 'Felipe', 'Davi', 'Renan', 'Maria'],
    'idade': [30, 22, 20, 25, 21],
    'salario': [3_000, 3_500, 4_200, 3_700, 5_000]
})

df

     nome  idade  salario
0    José     30     3000
1  Felipe     22     3500
2    Davi     20     4200
3   Renan     25     3700
4   Maria     21     5000

Certo, agora a primeira função que vamos ver é a *apply*, vamos dar um aumento salarial a todos os funcionários de 8%.

Porém, antes, visualize a sua função, o que ela faz e os parâmetros que recebe.

In [4]:
df.apply?

In [5]:
df['salario'] = df['salario'].apply(lambda x: x * 1.08)

In [6]:
df

     nome  idade  salario
0    José     30   3240.0
1  Felipe     22   3780.0
2    Davi     20   4536.0
3   Renan     25   3996.0
4   Maria     21   5400.0

Certo, agora aplicamos um aumento salarial para nossos funcionários, podemos criar mais *Series* para o nosso *DataFrame*, nesse caso, eu posso criar uma *Serie* nova da mesma forma que criavámos chaves no dicionário.

In [7]:
df['chefe'] = df.apply(lambda x: x['idade'] >= 30, axis=1)

In [8]:
df

     nome  idade  salario  chefe
0    José     30   3240.0   True
1  Felipe     22   3780.0  False
2    Davi     20   4536.0  False
3   Renan     25   3996.0  False
4   Maria     21   5400.0  False

Podemos, também usar a função *apply* juntamente com outras funções do *Python*.

Vamos criar um DataFrame passando os parâmetros nomeados, porém, por enquanto, sem dados, já que, vamos utilizar a biblioteca **numpy** para criar esses dados automaticamente.

In [9]:
dfs = pd.DataFrame(
    data=[],
    columns=['Lógica de Programação', 'Python', 'Data Science', 'HTML & CSS', 'JavaScript', 'React Native'],
    index=['Amanda', 'Camila', 'Cinthia', 'Gisele', 'Helen', 'Carol', 'Clara', 'Paula']
)

dfs

,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native
Amanda,NaN,NaN,NaN,NaN,NaN,NaN
Camila,NaN,NaN,NaN,NaN,NaN,NaN
Cinthia,NaN,NaN,NaN,NaN,NaN,NaN
Gisele,NaN,NaN,NaN,NaN,NaN,NaN
Helen,NaN,NaN,NaN,NaN,NaN,NaN
Carol,NaN,NaN,NaN,NaN,NaN,NaN
Clara,NaN,NaN,NaN,NaN,NaN,NaN
Paula,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Importando a biblioteca Numpy
import numpy as np

dfs = dfs.apply(lambda nota: np.random.uniform(low=5.0, high=10.0, size=8))
dfs

,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native
Amanda,5.852777,8.891548,7.658639,8.514665,6.253413,9.563425
Camila,7.091623,7.319502,5.805121,5.435369,6.957324,9.793992
Cinthia,7.317724,5.414574,7.577106,5.772767,6.663315,6.384313
Gisele,8.733468,6.023955,7.323408,8.616254,5.013421,6.136909
Helen,8.181469,6.907599,8.965590,8.583365,7.991204,7.865146
Carol,5.025371,8.516952,5.025447,9.984865,9.645095,7.984449
Clara,6.060399,5.246662,7.285350,8.709036,6.145658,5.350406
Paula,6.905347,5.754336,5.757631,6.309442,5.577598,8.829813

Nesse caso, tivemos números, bem feios gerados pela nossa função, dessa forma, podemos ajeitar isso e colocar quantas casas decimais queremos.

In [11]:
pd.options.display.float_format = '{:,.2f}'.format

In [12]:
dfs

,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native
Amanda,5.85,8.89,7.66,8.51,6.25,9.56
Camila,7.09,7.32,5.81,5.44,6.96,9.79
Cinthia,7.32,5.41,7.58,5.77,6.66,6.38
Gisele,8.73,6.02,7.32,8.62,5.01,6.14
Helen,8.18,6.91,8.97,8.58,7.99,7.87
Carol,5.03,8.52,5.03,9.98,9.65,7.98
Clara,6.06,5.25,7.29,8.71,6.15,5.35
Paula,6.91,5.75,5.76,6.31,5.58,8.83

Agora, vamos entender a função que fizemos acima:

```
(lambda nota: np.random.uniform(low=5.0, high=10.0, size=8))
```

Nesse caso acima, queremos um conjunto de números aleatórios entre um intervalo específico e uniforme, nesse sentindo, uniforme, significa dizer que os valores possuem a mesma probabilidade de serem gerados.

    low: É o limite inferior (mínimo) do intervalo.
    high: É o limite superior (máximo) do intervalo.
    size: É o número de valores aleatórios que você deseja gerar.

In [13]:
np.random?

In [14]:
np.random.uniform?

In [15]:
dfs

,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native
Amanda,5.85,8.89,7.66,8.51,6.25,9.56
Camila,7.09,7.32,5.81,5.44,6.96,9.79
Cinthia,7.32,5.41,7.58,5.77,6.66,6.38
Gisele,8.73,6.02,7.32,8.62,5.01,6.14
Helen,8.18,6.91,8.97,8.58,7.99,7.87
Carol,5.03,8.52,5.03,9.98,9.65,7.98
Clara,6.06,5.25,7.29,8.71,6.15,5.35
Paula,6.91,5.75,5.76,6.31,5.58,8.83

Algo que poderíamos adicionar a nosso *DataFrame* é o campo de Média, nesse caso, vamos utilizar a função *mean*.

In [16]:
dfs['media'] = dfs.mean(axis='columns')

In [17]:
dfs

,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native,media
Amanda,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,8.18,6.91,8.97,8.58,7.99,7.87,8.08
Carol,5.03,8.52,5.03,9.98,9.65,7.98,7.70
Clara,6.06,5.25,7.29,8.71,6.15,5.35,6.47
Paula,6.91,5.75,5.76,6.31,5.58,8.83,6.52

Dessa forma, agora que vimos a função *mean*, vamos voltar para um função que vimos na última aula, *map*.

Nesse caso, vamos utilizar a função para verificar quem está aprovado ou reprovado.

In [18]:
dfs['situacao'] = dfs['media'].map(lambda media: 'AP' if media > 7 else 'RP')

In [19]:
dfs

,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native,media,situacao
Amanda,5.85,8.89,7.66,8.51,6.25,9.56,7.79,AP
Camila,7.09,7.32,5.81,5.44,6.96,9.79,7.07,AP
Cinthia,7.32,5.41,7.58,5.77,6.66,6.38,6.52,RP
Gisele,8.73,6.02,7.32,8.62,5.01,6.14,6.97,RP
Helen,8.18,6.91,8.97,8.58,7.99,7.87,8.08,AP
Carol,5.03,8.52,5.03,9.98,9.65,7.98,7.70,AP
Clara,6.06,5.25,7.29,8.71,6.15,5.35,6.47,RP
Paula,6.91,5.75,5.76,6.31,5.58,8.83,6.52,RP

Certo, mas repare que as duas colunas criadas foram para o fim do *DataFrame* e claro que com o *Pandas* podemos especificar onde queremos que a nossa coluna fique alocada. Nesse caso, usaremos a função *insert* para especificar onde queremos que o nosso *DataFrame* esteja.

In [20]:
dfs.insert?

```
Signature: dfs.insert(loc: 'int', column: 'Hashable', value:

'S`alar | AnyArrayLike', allow_duplicates: 'bool | lib.NoDefault'

= pandas._libs.lib._NoDefault instance) -> 'None'
```

Isso é o que aparece quando pedimos ajuda na nossa função *insert*, dessa forma, sabemos agora que a função *insert* precisa de uma posição, um nome para coluna e valores.

In [22]:
# Vamos pegar primeiro os valores
situacao = dfs['media'].map(lambda media: 'AP' if media >= 7 else 'RP')
dfs.insert(0, 'Status', situacao)
dfs

,Status,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native,media,situacao
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79,AP
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07,AP
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52,RP
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97,RP
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08,AP
Carol,AP,5.03,8.52,5.03,9.98,9.65,7.98,7.70,AP
Clara,RP,6.06,5.25,7.29,8.71,6.15,5.35,6.47,RP
Paula,RP,6.91,5.75,5.76,6.31,5.58,8.83,6.52,RP

In [23]:
# Agora vamos deletar a coluna de situação para não deixarmos nosso DataFrame duplicado
del dfs['situacao']

In [24]:
dfs

,Status,Lógica de Programação,Python,Data Science,HTML & CSS,JavaScript,React Native,media
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08
Carol,AP,5.03,8.52,5.03,9.98,9.65,7.98,7.70
Clara,RP,6.06,5.25,7.29,8.71,6.15,5.35,6.47
Paula,RP,6.91,5.75,5.76,6.31,5.58,8.83,6.52

#### Rename

Continuando, vamos agora ver a função *rename*

In [25]:
dfs.rename?

In [28]:
dfs.rename(str.upper, axis='columns', inplace=True)

In [29]:
dfs

,STATUS,LÓGICA DE PROGRAMAÇÃO,PYTHON,DATA SCIENCE,HTML & CSS,JAVASCRIPT,REACT NATIVE,MEDIA
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08
Carol,AP,5.03,8.52,5.03,9.98,9.65,7.98,7.70
Clara,RP,6.06,5.25,7.29,8.71,6.15,5.35,6.47
Paula,RP,6.91,5.75,5.76,6.31,5.58,8.83,6.52

Então, agora pedimos para renomear todos os nomes das colunas para ficarem em *upper Case* ou melhor, deixarmos as letras em maiúsculo.

Outra coisa que podemos fazer com o *rename* é mudarmos uma coluna específica, da seguinte forma.

In [30]:
dfs.rename(columns={'LÓGICA DE PROGRAMAÇÃO': 'LOGICA'})

,STATUS,LOGICA,PYTHON,DATA SCIENCE,HTML & CSS,JAVASCRIPT,REACT NATIVE,MEDIA
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08
Carol,AP,5.03,8.52,5.03,9.98,9.65,7.98,7.70
Clara,RP,6.06,5.25,7.29,8.71,6.15,5.35,6.47
Paula,RP,6.91,5.75,5.76,6.31,5.58,8.83,6.52

Mas o que acontece se chamarmos de novo?

In [31]:
dfs

,STATUS,LÓGICA DE PROGRAMAÇÃO,PYTHON,DATA SCIENCE,HTML & CSS,JAVASCRIPT,REACT NATIVE,MEDIA
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08
Carol,AP,5.03,8.52,5.03,9.98,9.65,7.98,7.70
Clara,RP,6.06,5.25,7.29,8.71,6.15,5.35,6.47
Paula,RP,6.91,5.75,5.76,6.31,5.58,8.83,6.52

Quando chamamos de novo, a 'LÓGICA DE PROGRAMA', volta ao nosso *DataFrame*, por isso, é necessário passar o parâmetro *inplace*, para deixarmos salvo na memória do computador.

In [32]:
dfs.rename(columns={'LÓGICA DE PROGRAMAÇÃO': 'LOGICA'}, inplace=True)

In [33]:
dfs

,STATUS,LOGICA,PYTHON,DATA SCIENCE,HTML & CSS,JAVASCRIPT,REACT NATIVE,MEDIA
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08
Carol,AP,5.03,8.52,5.03,9.98,9.65,7.98,7.70
Clara,RP,6.06,5.25,7.29,8.71,6.15,5.35,6.47
Paula,RP,6.91,5.75,5.76,6.31,5.58,8.83,6.52

Outra funcionalidade do *rename* é que podemos aplicar ele nos nossos *index*, vamos usar o nosso outro DataFrame pra isso.

In [35]:
df.rename(
    index={0: 'A', 1: 'B', 2: 'C', 3: 'D', 4: 'E'},
    inplace=True
    )
df

     nome  idade  salario  chefe
A    José     30 3,240.00   True
B  Felipe     22 3,780.00  False
C    Davi     20 4,536.00  False
D   Renan     25 3,996.00  False
E   Maria     21 5,400.00  False

###apply

In [36]:
df.apply?

Vamos ver as funções *apply*, só que agora aplicada em *Series*.

In [37]:
df['nome']

A      José
B    Felipe
C      Davi
D     Renan
E     Maria
Name: nome, dtype: object

Veja que quando eu chamo uma coluna específica eu recebo uma *serie*, dessa forma, podemos utilizar a função *apply* em uma *serie* específica.

In [43]:
df['nome'].apply(lambda txt: txt.swapcase())

A      jOSÉ
B    fELIPE
C      dAVI
D     rENAN
E     mARIA
Name: nome, dtype: object

###Agg

In [44]:
df.agg?

Como vimos a função *agg* agrega uma ou mais operações à uma Series

Então, podemos aplicar várias função ao mesmo tempo dentro de uma *serie*.

In [45]:
# Vamos visualizar o valor mínimo, max, média e a soma total dos valores
df['salario'].agg(['min', 'max', 'mean', 'sum'])

min     3,240.00
max     5,400.00
mean    4,190.40
sum    20,952.00
Name: salario, dtype: float64

Só que perceba, ele retorna algo nada bonito visualmente, que é a *serie*, nesse caso, podemos transformar essa *serie* em um *DataFrame* de forma rápida.

In [46]:
df['salario'].agg(['min', 'max', 'mean', 'sum']).to_frame().transpose()

             min      max     mean       sum
salario 3,240.00 5,400.00 4,190.40 20,952.00

###Count

O count vai retornar o número de valores preenchidos de um *DataFrame* ou uma *Serie*. Vamos visualizar primeiro de *DataFrame*.

In [47]:
# Vamos criar outro
df2 = pd.DataFrame(
    {
        'Linguagem': ['Python', 'R', 'SQL', 'C', 'Java', 'Javascript', 'Elixir'],
        'Popularidade': ['Alta', 'Baixa', 'Altíssima', 'Média', 'Altíssima', 'Altíssima', 'Baixa'],
        'Versão': [3.10, 4.2, None, None, 11, 16, 1.12],
        'Desenvolvedores': [7_000_000, 500_000, 20_000_000, 3_500_000, 16_000_000, 25_000_000, 200_000],
        'Data de Lançamento': ['1991-02-20', '1993-08-03', '1986-01-01', '1972-01-01', '1995-05-23', '1995-12-04', '2012-01-01']
    }
)
df2

    Linguagem Popularidade  Versão  Desenvolvedores Data de Lançamento
0      Python         Alta    3.10          7000000         1991-02-20
1           R        Baixa    4.20           500000         1993-08-03
2         SQL    Altíssima     NaN         20000000         1986-01-01
3           C        Média     NaN          3500000         1972-01-01
4        Java    Altíssima   11.00         16000000         1995-05-23
5  Javascript    Altíssima   16.00         25000000         1995-12-04
6      Elixir        Baixa    1.12           200000         2012-01-01

In [48]:
df2.count?

In [49]:
df2.count(axis='columns')

0    5
1    5
2    4
3    4
4    5
5    5
6    5
dtype: int64

Perceba que ele retornou exatamente os valores preechidos em cada coluna.

Outra coisa que podemos fazer, também, é gerar um DataFrame com esses dados, para termos uma melhor visualização.

In [51]:
df2.count(axis='index').to_frame().transpose()

   Linguagem  Popularidade  Versão  Desenvolvedores  Data de Lançamento
0          7             7       5                7                   7

Agora, na questão de *series*, precisamos apenas verificar as colunas

In [53]:
df2['Versão'].count()

5

###value_counts

In [54]:
df.value_counts?

Essa função, vai retornar a quatidade de valores que possuímos dentro de uma determinada *serie*, nesse caso, podemos trabalhar com a popularidade, por exemplo.

In [55]:
df2['Popularidade']

0         Alta
1        Baixa
2    Altíssima
3        Média
4    Altíssima
5    Altíssima
6        Baixa
Name: Popularidade, dtype: object

In [56]:
df2.value_counts(subset='Popularidade')

Popularidade
Altíssima    3
Baixa        2
Alta         1
Média        1
dtype: int64

Nesse caso, precisamos passar a serie em questão no parâmetro de *subset*, que seria o sub conjunto que temos.

###sort_values

Outra função que temos é para ordenar o nosso *DataFrame*, nesse caso, precisamos passar uma coluna específica para utilizar essa função, assim, teremos o parâmetro **by**, que informa onde será a ordenação.

In [59]:
df2.sort_values(by='Versão')

    Linguagem Popularidade  Versão  Desenvolvedores Data de Lançamento
6      Elixir        Baixa    1.12           200000         2012-01-01
0      Python         Alta    3.10          7000000         1991-02-20
1           R        Baixa    4.20           500000         1993-08-03
4        Java    Altíssima   11.00         16000000         1995-05-23
5  Javascript    Altíssima   16.00         25000000         1995-12-04
2         SQL    Altíssima     NaN         20000000         1986-01-01
3           C        Média     NaN          3500000         1972-01-01

###drop

In [60]:
dfs.head()

,STATUS,LOGICA,PYTHON,DATA SCIENCE,HTML & CSS,JAVASCRIPT,REACT NATIVE,MEDIA
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08

Agora vamos supor, que eu não queira mais o campo de Status e média, eu poderia simplesmente utilizar nossa função **del** em cada uma ou podemos utilizar a função *drop*.

In [64]:
dfs.drop(['MEDIA', 'STATUS'], axis='columns')

         LOGICA  PYTHON  DATA SCIENCE  HTML & CSS  JAVASCRIPT  REACT NATIVE
Amanda     5.85    8.89          7.66        8.51        6.25          9.56
Camila     7.09    7.32          5.81        5.44        6.96          9.79
Cinthia    7.32    5.41          7.58        5.77        6.66          6.38
Gisele     8.73    6.02          7.32        8.62        5.01          6.14
Helen      8.18    6.91          8.97        8.58        7.99          7.87
Carol      5.03    8.52          5.03        9.98        9.65          7.98
Clara      6.06    5.25          7.29        8.71        6.15          5.35
Paula      6.91    5.75          5.76        6.31        5.58          8.83

In [65]:
dfs

,STATUS,LOGICA,PYTHON,DATA SCIENCE,HTML & CSS,JAVASCRIPT,REACT NATIVE,MEDIA
Amanda,AP,5.85,8.89,7.66,8.51,6.25,9.56,7.79
Camila,AP,7.09,7.32,5.81,5.44,6.96,9.79,7.07
Cinthia,RP,7.32,5.41,7.58,5.77,6.66,6.38,6.52
Gisele,RP,8.73,6.02,7.32,8.62,5.01,6.14,6.97
Helen,AP,8.18,6.91,8.97,8.58,7.99,7.87,8.08
Carol,AP,5.03,8.52,5.03,9.98,9.65,7.98,7.70
Clara,RP,6.06,5.25,7.29,8.71,6.15,5.35,6.47
Paula,RP,6.91,5.75,5.76,6.31,5.58,8.83,6.52

Só que nesse caso, precisamos também utilizar o nosso *inplace* para salvar na memória do nosso computador.

In [66]:
dfs.drop(['MEDIA', 'STATUS'], axis='columns', inplace=True)

In [67]:
dfs

         LOGICA  PYTHON  DATA SCIENCE  HTML & CSS  JAVASCRIPT  REACT NATIVE
Amanda     5.85    8.89          7.66        8.51        6.25          9.56
Camila     7.09    7.32          5.81        5.44        6.96          9.79
Cinthia    7.32    5.41          7.58        5.77        6.66          6.38
Gisele     8.73    6.02          7.32        8.62        5.01          6.14
Helen      8.18    6.91          8.97        8.58        7.99          7.87
Carol      5.03    8.52          5.03        9.98        9.65          7.98
Clara      6.06    5.25          7.29        8.71        6.15          5.35
Paula      6.91    5.75          5.76        6.31        5.58          8.83